### ISSUE TITLE
Admin overview too long

### ISSUE THREAD

**Issue by yagarea** [chamik/rozrazovak#3]
Navrhuji změnit:
```
<main class="flex min-h-screen flex-col w-full">
```
$\downarrow$
```
<main class="flex flex-col w-full" >
```

Protože  jinak je stránka scrollovateltená ikdyž nic neobsahuje.

**Comment by chamik** [comment]
yes, tohle tam je jen kvůli tomu, aby to nevypadalo *tolik* prázdně :D až tam něco bude (aktuální statistiky testů), tak to půjde pryč
