### ISSUE TITLE
Login with Teacher email

### ISSUE THREAD

**Issue by pajasry** [chamik/rozrazovak#4]
Login with teacher email on deployed web does not work. This may be also related to students emails.
![image](https://github.com/chamik/rozrazovak/assets/27287981/0a05e444-c174-42c0-8926-c16995cd94d7)

**Comment by chamik** [comment]
Works fine as far as I can tell. This is probably because you're not added to the [teacher email list](https://github.com/chamik/rozrazovak/blob/main/.env-example#L27). DM me your gmail and I'll add you ;)

**Comment by pajasry** [comment]
Ought, I forgot about that part, thought it validates teacher using some sort of google groups. It's no need to add me to the list. But the UI error would be great (contact the almighty administrator etc.)

**Comment by chamik** [comment]
when auth fails, it should redirect you to `/begone` (added the page itself in 0eff207)
